name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! We truly appreciate your input and will use the information you provide below to try and make the game better.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: githash
    attributes:
      label: Version
      description: What version were you on?
      options:
        - Joker Build
        - Itemless Build
        - Prototype Build
        - Other (fill out below)
      default: 3
    validations:
      required: true
  - type: textarea
    id: platform
    attributes:
      label: What emulator/platform are you seeing the problem on?
    validations:
      required: true
